version: '3.4'

services:
  imersaopython:
    container_name: imersaopython
    build:
      context: .
      dockerfile: ./Dockerfile
    command: tail -f /dev/null
    ports:
      - 8003:8003
    volumes:
      - .:/app
    networks:
      - private
    depends_on: 
      - database
  
  database:
    container_name: database
    image: postgres:12.1-alpine
    ports:
      - 5433:5432
    expose: 
      - '5433'
    volumes:
      - imersaopython_pgdata:/var/lib/postgresql/data
    command: -p 5433
    networks:
      - private
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

networks:
    private:

volumes:  
    imersaopython_pgdata: