# Generated by Django 3.2.5 on 2021-07-24 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupomdesconto',
            name='codigo',
            field=models.CharField(max_length=8, unique=True, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(blank=True, max_length=200, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cep',
            field=models.CharField(blank=True, max_length=50, verbose_name='cep'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 19, 18, 29, 503561), verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='numero'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(max_length=20, verbose_name='pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='rua',
            field=models.CharField(max_length=200, verbose_name='rua'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(max_length=30, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='troco',
            field=models.CharField(blank=True, max_length=20, verbose_name='troco'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.CharField(max_length=200, verbose_name='usuario'),
        ),
    ]
