# Generated by Django 3.2.5 on 2021-07-26 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_alter_pedido_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 20, 50, 41, 608089), verbose_name='data'),
        ),
    ]
